//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enum2.DemoSoap.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetChallengeResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetChallengeResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChallengeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QrUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Challenge {
            get {
                return this.ChallengeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChallengeField, value) != true)) {
                    this.ChallengeField = value;
                    this.RaisePropertyChanged("Challenge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string QrUrl {
            get {
                return this.QrUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.QrUrlField, value) != true)) {
                    this.QrUrlField = value;
                    this.RaisePropertyChanged("QrUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SoapSoap")]
    public interface SoapSoap {
        
        // CODEGEN: Generating message contract since element name consumerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChallenge", ReplyAction="*")]
        Enum2.DemoSoap.ServiceReference1.GetChallengeResponse GetChallenge(Enum2.DemoSoap.ServiceReference1.GetChallengeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChallenge", ReplyAction="*")]
        System.Threading.Tasks.Task<Enum2.DemoSoap.ServiceReference1.GetChallengeResponse> GetChallengeAsync(Enum2.DemoSoap.ServiceReference1.GetChallengeRequest request);
        
        // CODEGEN: Generating message contract since element name consumerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserAnswer", ReplyAction="*")]
        Enum2.DemoSoap.ServiceReference1.CheckUserAnswerResponse CheckUserAnswer(Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserAnswer", ReplyAction="*")]
        System.Threading.Tasks.Task<Enum2.DemoSoap.ServiceReference1.CheckUserAnswerResponse> CheckUserAnswerAsync(Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequest request);
        
        // CODEGEN: Generating message contract since element name lang from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetErrDesc", ReplyAction="*")]
        Enum2.DemoSoap.ServiceReference1.GetErrDescResponse GetErrDesc(Enum2.DemoSoap.ServiceReference1.GetErrDescRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetErrDesc", ReplyAction="*")]
        System.Threading.Tasks.Task<Enum2.DemoSoap.ServiceReference1.GetErrDescResponse> GetErrDescAsync(Enum2.DemoSoap.ServiceReference1.GetErrDescRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChallengeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChallenge", Namespace="http://tempuri.org/", Order=0)]
        public Enum2.DemoSoap.ServiceReference1.GetChallengeRequestBody Body;
        
        public GetChallengeRequest() {
        }
        
        public GetChallengeRequest(Enum2.DemoSoap.ServiceReference1.GetChallengeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetChallengeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consumerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userIp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string crc;
        
        public GetChallengeRequestBody() {
        }
        
        public GetChallengeRequestBody(string consumerId, string email, string userIp, string crc) {
            this.consumerId = consumerId;
            this.email = email;
            this.userIp = userIp;
            this.crc = crc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChallengeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChallengeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Enum2.DemoSoap.ServiceReference1.GetChallengeResponseBody Body;
        
        public GetChallengeResponse() {
        }
        
        public GetChallengeResponse(Enum2.DemoSoap.ServiceReference1.GetChallengeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetChallengeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Enum2.DemoSoap.ServiceReference1.GetChallengeResult GetChallengeResult;
        
        public GetChallengeResponseBody() {
        }
        
        public GetChallengeResponseBody(Enum2.DemoSoap.ServiceReference1.GetChallengeResult GetChallengeResult) {
            this.GetChallengeResult = GetChallengeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserAnswerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserAnswer", Namespace="http://tempuri.org/", Order=0)]
        public Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequestBody Body;
        
        public CheckUserAnswerRequest() {
        }
        
        public CheckUserAnswerRequest(Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserAnswerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consumerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string challenge;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string response;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string addname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string userIp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string crc;
        
        public CheckUserAnswerRequestBody() {
        }
        
        public CheckUserAnswerRequestBody(string consumerId, string email, string challenge, string response, string addname, string userIp, string crc) {
            this.consumerId = consumerId;
            this.email = email;
            this.challenge = challenge;
            this.response = response;
            this.addname = addname;
            this.userIp = userIp;
            this.crc = crc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserAnswerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserAnswerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Enum2.DemoSoap.ServiceReference1.CheckUserAnswerResponseBody Body;
        
        public CheckUserAnswerResponse() {
        }
        
        public CheckUserAnswerResponse(Enum2.DemoSoap.ServiceReference1.CheckUserAnswerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserAnswerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CheckUserAnswerResult;
        
        public CheckUserAnswerResponseBody() {
        }
        
        public CheckUserAnswerResponseBody(int CheckUserAnswerResult) {
            this.CheckUserAnswerResult = CheckUserAnswerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetErrDescRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetErrDesc", Namespace="http://tempuri.org/", Order=0)]
        public Enum2.DemoSoap.ServiceReference1.GetErrDescRequestBody Body;
        
        public GetErrDescRequest() {
        }
        
        public GetErrDescRequest(Enum2.DemoSoap.ServiceReference1.GetErrDescRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetErrDescRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int errorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lang;
        
        public GetErrDescRequestBody() {
        }
        
        public GetErrDescRequestBody(int errorCode, string lang) {
            this.errorCode = errorCode;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetErrDescResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetErrDescResponse", Namespace="http://tempuri.org/", Order=0)]
        public Enum2.DemoSoap.ServiceReference1.GetErrDescResponseBody Body;
        
        public GetErrDescResponse() {
        }
        
        public GetErrDescResponse(Enum2.DemoSoap.ServiceReference1.GetErrDescResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetErrDescResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetErrDescResult;
        
        public GetErrDescResponseBody() {
        }
        
        public GetErrDescResponseBody(string GetErrDescResult) {
            this.GetErrDescResult = GetErrDescResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoapSoapChannel : Enum2.DemoSoap.ServiceReference1.SoapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapSoapClient : System.ServiceModel.ClientBase<Enum2.DemoSoap.ServiceReference1.SoapSoap>, Enum2.DemoSoap.ServiceReference1.SoapSoap {
        
        public SoapSoapClient() {
        }
        
        public SoapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Enum2.DemoSoap.ServiceReference1.GetChallengeResponse Enum2.DemoSoap.ServiceReference1.SoapSoap.GetChallenge(Enum2.DemoSoap.ServiceReference1.GetChallengeRequest request) {
            return base.Channel.GetChallenge(request);
        }
        
        public Enum2.DemoSoap.ServiceReference1.GetChallengeResult GetChallenge(string consumerId, string email, string userIp, string crc) {
            Enum2.DemoSoap.ServiceReference1.GetChallengeRequest inValue = new Enum2.DemoSoap.ServiceReference1.GetChallengeRequest();
            inValue.Body = new Enum2.DemoSoap.ServiceReference1.GetChallengeRequestBody();
            inValue.Body.consumerId = consumerId;
            inValue.Body.email = email;
            inValue.Body.userIp = userIp;
            inValue.Body.crc = crc;
            Enum2.DemoSoap.ServiceReference1.GetChallengeResponse retVal = ((Enum2.DemoSoap.ServiceReference1.SoapSoap)(this)).GetChallenge(inValue);
            return retVal.Body.GetChallengeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Enum2.DemoSoap.ServiceReference1.GetChallengeResponse> Enum2.DemoSoap.ServiceReference1.SoapSoap.GetChallengeAsync(Enum2.DemoSoap.ServiceReference1.GetChallengeRequest request) {
            return base.Channel.GetChallengeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Enum2.DemoSoap.ServiceReference1.GetChallengeResponse> GetChallengeAsync(string consumerId, string email, string userIp, string crc) {
            Enum2.DemoSoap.ServiceReference1.GetChallengeRequest inValue = new Enum2.DemoSoap.ServiceReference1.GetChallengeRequest();
            inValue.Body = new Enum2.DemoSoap.ServiceReference1.GetChallengeRequestBody();
            inValue.Body.consumerId = consumerId;
            inValue.Body.email = email;
            inValue.Body.userIp = userIp;
            inValue.Body.crc = crc;
            return ((Enum2.DemoSoap.ServiceReference1.SoapSoap)(this)).GetChallengeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Enum2.DemoSoap.ServiceReference1.CheckUserAnswerResponse Enum2.DemoSoap.ServiceReference1.SoapSoap.CheckUserAnswer(Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequest request) {
            return base.Channel.CheckUserAnswer(request);
        }
        
        public int CheckUserAnswer(string consumerId, string email, string challenge, string response, string addname, string userIp, string crc) {
            Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequest inValue = new Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequest();
            inValue.Body = new Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequestBody();
            inValue.Body.consumerId = consumerId;
            inValue.Body.email = email;
            inValue.Body.challenge = challenge;
            inValue.Body.response = response;
            inValue.Body.addname = addname;
            inValue.Body.userIp = userIp;
            inValue.Body.crc = crc;
            Enum2.DemoSoap.ServiceReference1.CheckUserAnswerResponse retVal = ((Enum2.DemoSoap.ServiceReference1.SoapSoap)(this)).CheckUserAnswer(inValue);
            return retVal.Body.CheckUserAnswerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Enum2.DemoSoap.ServiceReference1.CheckUserAnswerResponse> Enum2.DemoSoap.ServiceReference1.SoapSoap.CheckUserAnswerAsync(Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequest request) {
            return base.Channel.CheckUserAnswerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Enum2.DemoSoap.ServiceReference1.CheckUserAnswerResponse> CheckUserAnswerAsync(string consumerId, string email, string challenge, string response, string addname, string userIp, string crc) {
            Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequest inValue = new Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequest();
            inValue.Body = new Enum2.DemoSoap.ServiceReference1.CheckUserAnswerRequestBody();
            inValue.Body.consumerId = consumerId;
            inValue.Body.email = email;
            inValue.Body.challenge = challenge;
            inValue.Body.response = response;
            inValue.Body.addname = addname;
            inValue.Body.userIp = userIp;
            inValue.Body.crc = crc;
            return ((Enum2.DemoSoap.ServiceReference1.SoapSoap)(this)).CheckUserAnswerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Enum2.DemoSoap.ServiceReference1.GetErrDescResponse Enum2.DemoSoap.ServiceReference1.SoapSoap.GetErrDesc(Enum2.DemoSoap.ServiceReference1.GetErrDescRequest request) {
            return base.Channel.GetErrDesc(request);
        }
        
        public string GetErrDesc(int errorCode, string lang) {
            Enum2.DemoSoap.ServiceReference1.GetErrDescRequest inValue = new Enum2.DemoSoap.ServiceReference1.GetErrDescRequest();
            inValue.Body = new Enum2.DemoSoap.ServiceReference1.GetErrDescRequestBody();
            inValue.Body.errorCode = errorCode;
            inValue.Body.lang = lang;
            Enum2.DemoSoap.ServiceReference1.GetErrDescResponse retVal = ((Enum2.DemoSoap.ServiceReference1.SoapSoap)(this)).GetErrDesc(inValue);
            return retVal.Body.GetErrDescResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Enum2.DemoSoap.ServiceReference1.GetErrDescResponse> Enum2.DemoSoap.ServiceReference1.SoapSoap.GetErrDescAsync(Enum2.DemoSoap.ServiceReference1.GetErrDescRequest request) {
            return base.Channel.GetErrDescAsync(request);
        }
        
        public System.Threading.Tasks.Task<Enum2.DemoSoap.ServiceReference1.GetErrDescResponse> GetErrDescAsync(int errorCode, string lang) {
            Enum2.DemoSoap.ServiceReference1.GetErrDescRequest inValue = new Enum2.DemoSoap.ServiceReference1.GetErrDescRequest();
            inValue.Body = new Enum2.DemoSoap.ServiceReference1.GetErrDescRequestBody();
            inValue.Body.errorCode = errorCode;
            inValue.Body.lang = lang;
            return ((Enum2.DemoSoap.ServiceReference1.SoapSoap)(this)).GetErrDescAsync(inValue);
        }
    }
}
